"use strict";
window.ProfileViews = (() => {
  const {h,icon,link,pageHead,bar}=UI;
  function awards(){
    return `<section class="section"><div class="section-head"><h2>Tu colección de insignias</h2><span class="tiny">Hitos históricos · sin recompensas aleatorias</span></div><div class="g-award-grid">${GameRules.badges(Progress.state).map(b=>`<article class="card g-award ${b.earned?'earned':''}"><div class="g-award-icon">${icon(b.icon)}</div><h3>${h(b.title)}</h3><p>${h(b.text)}</p>${bar(Math.min(100,Math.round(b.value/b.target*100)),b.title)}<span class="badge ${b.earned?'accent':''}">${b.earned?'Conseguida':`${Math.min(b.value,b.target)}/${b.target}`}</span></article>`).join('')}</div></section>`;
  }
  function calendar(){
    const active=new Set(Progress.state.days);
    return `<div class="g-activity-days" aria-label="Actividad de los últimos 14 días">${Array.from({length:14},(_,index)=>{const d=new Date();d.setDate(d.getDate()-13+index);const key=GameRules.dateKey(d),on=active.has(key);return `<span class="g-day ${on?'active':''}" title="${key}: ${on?'con práctica':'sin actividad registrada'}" aria-label="${key}: ${on?'con práctica':'sin actividad registrada'}"><small>${new Intl.DateTimeFormat('es',{weekday:'narrow'}).format(d)}</small><i>${d.getDate()}</i></span>`;}).join('')}</div>`;
  }
  function rules(){
    const s=GameRules.summary(Progress.state);
    const names={lessons:'Lecciones',exercises:'Ejercicios',challenges:'Retos',predictions:'Predicciones correctas',debug:'Diagnósticos autoevaluados',quizzes:'Quiz',mastery:'Nodos con 3 estrellas',incidents:'Incidentes',missions:'Misiones recogidas'};
    return `<section class="section card"><h2>XP transparentes. Aprendizaje primero.</h2><div class="grid-2"><div><h3>Cómo se consiguen</h3><dl class="g-rules-list"><div><dt>Primera realización de una lección</dt><dd>25 XP</dd></div><div><dt>Ejercicio básico / intermedio / avanzado</dt><dd>35 / 55 / 80 XP</dd></div><div><dt>Reto básico / intermedio / avanzado</dt><dd>120 / 180 / 240 XP</dd></div><div><dt>Predicción correcta / diagnóstico autoevaluado</dt><dd>40 / 30 XP</dd></div><div><dt>Primera entrega de un quiz</dt><dd>20 XP</dd></div><div><dt>Por cada acierto de tu mejor quiz</dt><dd>15 XP</dd></div><div><dt>Primer 100% en cada quiz</dt><dd>30 XP extra</dd></div><div><dt>Primer dominio de un módulo (3 estrellas)</dt><dd>100 XP</dd></div><div><dt>Decisión correcta de un incidente</dt><dd>25 XP</dd></div><div><dt>Resolver incidente 1 / 2 / 3</dt><dd>125 / 225 / 325 XP extra</dd></div></dl></div><div><h3>Tu balance actual</h3><dl class="g-rules-list">${s.breakdown.map(x=>`<div><dt>${names[x.kind]}</dt><dd>${x.xp.toLocaleString('es-ES')} XP</dd></div>`).join('')}<div class="g-total"><dt>Total</dt><dd>${s.xp.toLocaleString('es-ES')} XP</dd></div></dl></div></div><p class="tiny">Mejorar tu quiz solo suma los nuevos aciertos y, cuando procede, el bonus de perfección. Repetir una nota no genera más XP. Las misiones añaden la cantidad indicada al recogerlas, una sola vez. Una visita, una pista o ejecutar código no da puntos por sí solo.</p><div class="callout"><strong>No es una nota académica.</strong> Lecciones, ejercicios, retos y diagnósticos son autoevaluados. Quiz, predicciones e incidentes se corrigen automáticamente en el navegador. No hay verificación externa ni protección antitrampas: es una herramienta personal, no un examen ni un ranking de clase. Los rangos son nombres del juego, no certificaciones profesionales.</div><p class="tiny">Los XP y las estrellas conservan tus realizaciones históricas aunque marques una actividad como pendiente. Reiniciar elimina ambos. La racha puede volver a cero al descansar, pero no pierdes XP, nivel ni insignias. Los objetivos diarios no dan XP extra ni bloquean contenido.</p></section>`;
  }
  function profile(){
    const p=Progress.state.game.profile,s=GameRules.summary(Progress.state);
    return pageHead('PERFIL DE OPERACIONES','Una trayectoria que es tuya.','Personaliza tu espacio, elige un objetivo realista y revisa los hitos que has conseguido.',link('#/progress','Copia de seguridad','secondary','download'))+
      GameViews.player()+`<section class="section grid-2"><div class="card"><h2>Tu identidad</h2><form id="game-profile-form" class="g-profile-form"><label for="game-alias">Alias de operaciones</label><input id="game-alias" name="alias" maxlength="24" value="${h(p.alias)}" autocomplete="off"><p class="tiny">Usa un alias, no necesitas escribir tu nombre real. Solo se guarda en este navegador y en las copias que exportes.</p><label for="game-goal">Objetivo personal de actividades al día</label><select id="game-goal" name="goal">${[1,3,5].map(n=>`<option value="${n}" ${n===p.goal?'selected':''}>${n} ${n===1?'actividad':'actividades'} distintas</option>`).join('')}</select><label class="g-check-label"><input type="checkbox" name="effects" ${p.effects?'checked':''}> Animaciones suaves de recompensa</label><button class="btn primary" type="submit">Guardar perfil ${icon('check')}</button></form><h3 class="section">Elige tu emblema</h3><div class="g-avatar-options">${GameData.avatars.map(a=>`<button class="g-avatar-option ${a.id===p.avatar?'selected':''}" data-action="game-avatar" data-id="${a.id}" aria-pressed="${a.id===p.avatar}">${icon(a.icon)}<span>${h(a.title)}</span></button>`).join('')}</div></div><div class="card"><h2>Recompensas visuales</h2><p class="muted">Desbloquea colores de acento al subir de nivel. El contenido nunca se bloquea.</p><div class="g-palette-options">${GameData.palettes.map(t=>`<button class="g-palette-option ${t.id===p.palette?'selected':''}" data-action="game-palette" data-id="${t.id}" ${s.level<t.level?'disabled':''} aria-pressed="${t.id===p.palette}"><span class="g-swatch swatch-${t.id}" aria-hidden="true"></span><span><strong>${h(t.title)}</strong><small>${s.level<t.level?'Se desbloquea en nivel '+t.level:t.id===p.palette?'Tema equipado':'Disponible'}</small></span>${icon(s.level<t.level?'shield':t.id===p.palette?'check':'spark')}</button>`).join('')}</div><h3 class="section">Últimos 14 días</h3>${calendar()}<p class="tiny">Los días sin actividad no restan puntos. Constancia también significa retomar después de una pausa.</p></div></section>`+
      awards()+`<section class="section card"><h2>Tu escalera de niveles</h2><div class="g-level-list">${GameData.ranks.map((r,i)=>`<div class="g-level ${s.level===i+1?'current':''} ${s.level>i+1?'completed':''}"><span>${s.level>i+1?icon('check'):i+1}</span><strong>${h(r.title)}</strong><small>${r.xp.toLocaleString('es-ES')} XP${s.level===i+1?' · Nivel actual':''}</small></div>`).join('')}</div></section>`+rules();
  }
  return {profile,awards,rules};
})();
