"use strict";
window.GameViews = (() => {
  const {h,icon,link,bar,pageHead}=UI;
  const state=()=>Progress.state;
  const fmt=n=>n.toLocaleString('es-ES');
  function xpTag(kind,id){
    const earned=state().game.earned[kind]?.includes(id);
    return `<span class="g-xp-tag">${icon(earned?'check':'spark')}${earned?'XP conseguidos':'+'+GameRules.points(kind,id)+' XP'}</span>`;
  }
  function player(){
    const s=state(),g=s.game,p=g.profile,rank=GameRules.summary(s),d=GameRules.daily(s);
    return `<section class="g-player card"><div class="g-player-head"><div class="g-emblem" aria-hidden="true">${icon(p.avatar)}<span>${rank.level}</span></div><div><p class="eyebrow">TU IDENTIDAD DE OPERACIONES</p><h2>${h(p.alias)}</h2><p>${h(rank.title)}</p></div>${link('#/profile','Perfil','ghost','edit')}</div><div class="g-xp-heading"><strong>${fmt(rank.xp)} <small>XP</small></strong><span>NIVEL ${rank.level} / ${GameData.ranks.length}</span></div>${bar(rank.percent,'Avance al siguiente nivel')}<p class="g-next-rank">${rank.next?`${fmt(rank.remaining)} XP para nivel ${rank.level+1} · ${h(rank.next.title)}`:'Nivel máximo alcanzado. Sigue aprendiendo y completando tu colección.'}</p><div class="g-player-stats"><div><strong>${rank.mastered}<small>/14</small></strong><span>Módulos con 3 estrellas</span></div><div><strong>${GameRules.badges(s).filter(b=>b.earned).length}<small>/12</small></strong><span>Insignias</span></div><div><strong>${s.days.length}</strong><span>Días de práctica</span></div></div></section>`;
  }
  function daily(){
    const s=state(),d=GameRules.daily(s);
    return `<section class="card g-daily"><div class="section-head"><div><p class="eyebrow">OBJETIVO PERSONAL · HOY</p><h2>${d.done>=d.goal?'Objetivo conseguido. Buen trabajo.':'Un poco de práctica. Un paso real.'}</h2></div><span class="g-goal-count">${d.done}<small>/${d.goal}</small></span></div>${bar(d.percent,'Objetivo personal de hoy')}<div class="g-daily-bottom"><p>Actividades distintas de aprendizaje o repaso. Sin límite de tiempo ni pérdida de XP. Racha actual: ${Progress.streak()} ${Progress.streak()===1?'día':'días'}.</p><a class="text-link" href="#/profile">Ajustar objetivo ${icon('edit')}</a></div></section>`;
  }
  function home(){
    const s=state(),next=Progress.next(),missions=GameRules.missions(s),suggested=missions.find(m=>m.ready&&!m.claimed)||missions.find(m=>!m.claimed),rank=GameRules.summary(s);
    return pageHead('PYTHON OPS · FUNDAMENTOS DE PYTHON · 2º ASIR','Tu próxima misión empieza aquí.','Aprende Python, resuelve problemas de sistemas y construye tu propia trayectoria. A tu ritmo.',`<span class="g-live-label"><i></i> LABORATORIO PERSONAL</span>`)+
      `<div class="g-home-grid">${player()}<section class="g-briefing card"><p class="eyebrow">${s.lastLesson?'RETOMA EL CONTROL':'PRIMERA MISIÓN'}</p><h2>De tu primera línea<br>a pensar como un sysadmin.</h2><p>14 módulos. Un entorno simulado. Las habilidades las construyes tú.</p><div class="g-next-lesson"><span class="g-mini-terminal">${icon('terminal')}</span><div><small>MÓDULO ${String(next.module).padStart(2,'0')}</small><strong>${h(next.title)}</strong></div></div><div class="button-row">${link('#/lesson/'+next.id,s.lastLesson?'Continuar aprendiendo':'Comenzar misión','primary')}${link('#/operations','Ver campaña','secondary','layers')}</div></section></div>`+
      daily()+`<section class="section"><div class="section-head"><h2>Activa tu red de conocimientos</h2><a class="text-link" href="#/operations">Explorar campaña ${icon('arrow')}</a></div><div class="g-network-strip" aria-label="Mapa de 14 módulos">${Course.modules.map(m=>{const n=GameRules.stars(s,m.id).filter(Boolean).length;return `<a href="#/module/${m.id}" class="g-network-node ${n===3?'is-mastered':n?'is-active':''}" aria-label="Módulo ${m.id}: ${h(m.title)}. ${n} de 3 estrellas"><span>${n===3?icon('check'):String(m.id).padStart(2,'0')}</span><small>${n}/3</small></a>`;}).join('')}</div></section>`+
      `<section class="section g-home-lower"><div class="card"><div class="section-head"><h2>Tu siguiente recompensa</h2>${icon('flag')}</div>${suggested?missionCard(suggested,true):'<p>Has completado todas las misiones. Revisa tus insignias y sigue practicando.</p>'}<a class="text-link" href="#/missions">Tablón de misiones ${icon('arrow')}</a></div><article class="card g-incident-promo"><p class="eyebrow">INCIDENTES DE OPERACIONES</p><h2>Algo falla.<br>Tu código tiene la respuesta.</h2><p>Diagnostica 3 incidentes con corrección automática. Sin cronómetro, sin vidas y sin tocar sistemas reales.</p>${link('#/incident/i01','Abrir primer incidente','secondary','bug')}<small>Hasta 900 XP entre los 3 incidentes.</small></article></section>`+
      `<section class="section"><div class="section-head"><h2>Aprende. Practica. Comprueba.</h2><span class="tiny">${Progress.stats().percent}% del recorrido original</span></div><div class="grid-3"><article class="card"><p class="eyebrow">01 · CONCEPTOS</p><h3>28 lecciones guiadas</h3><p class="muted">Explicación, ejemplos y práctica con contexto ASIR.</p>${link('#/modules','Abrir temario','ghost','book')}</article><article class="card"><p class="eyebrow">02 · PRÁCTICA</p><h3>56 ejercicios + 12 retos</h3><p class="muted">Pistas y soluciones sin penalización. XP por tu primera realización.</p>${link('#/exercises','Elegir ejercicio','ghost','code')}</article><article class="card"><p class="eyebrow">03 · DIAGNÓSTICO</p><h3>Predice y depura</h3><p class="muted">14 predicciones y 14 diagnósticos para entender qué hace el código.</p>${link('#/predict','Predecir salida','ghost','eye')}</article></div></section>`;
  }
  function node(m){
    const stars=GameRules.stars(state(),m.id),n=stars.filter(Boolean).length;
    return `<a class="g-module-node ${n===3?'is-mastered':''}" href="#/module/${m.id}"><div class="g-node-top"><span class="g-node-code">NODO ${String(m.id).padStart(2,'0')}</span>${icon(n===3?'check':'terminal')}</div><h3>${h(m.title)}</h3><div class="g-stars" aria-label="${n} de 3 estrellas: ${['lecciones','práctica','quiz'].map((label,i)=>label+(stars[i]?' conseguida':' pendiente')).join(', ')}">${stars.map((on,i)=>`<span class="${on?'earned':''}" aria-hidden="true" title="${['2 lecciones','2 ejercicios','Quiz ≥ 80%'][i]}">★</span>`).join('')}<small>${n===3?'Dominio conseguido':`${n}/3 objetivos`}</small></div></a>`;
  }
  function operations(){
    const mastered=GameRules.mastery(state());
    return pageHead('CAMPAÑA PYTHON OPS','Tu infraestructura de conocimientos.','Cada módulo es un nodo: aprende, practica y demuestra lo que has entendido. Todos los contenidos están disponibles desde el principio.')+
      `<div class="g-campaign-summary card"><div><span class="g-large-number">${mastered.length}<small>/14</small></span><p>Nodos con 3 estrellas</p></div><div><h2>Tres evidencias. Un nodo dominado.</h2><div class="g-star-legend"><span>★ 2 lecciones completadas</span><span>★ 2 ejercicios realizados</span><span>★ Mejor quiz ≥ 80%</span></div><p class="tiny">+100 XP al conseguir las tres. Las estrellas y los XP son logros históricos: desmarcar una actividad no los elimina ni permite volver a cobrarlos. No equivalen a una calificación.</p></div></div>`+
      GameData.sectors.map((sector,index)=>{const inc=GameData.incidents.find(i=>i.id===sector.incident),done=GameRules.incidentDone(state(),inc.id),nodes=Course.modules.filter(m=>m.id>=sector.from&&m.id<=sector.to);return `<section class="section g-sector"><div class="g-sector-heading"><span class="g-sector-icon">${icon(sector.icon)}</span><div><p class="eyebrow">SECTOR ${String(index+1).padStart(2,'0')} · MÓDULOS ${sector.from}–${sector.to}</p><h2>${h(sector.title)}</h2><p>${h(sector.subtitle)}</p></div><span class="badge accent">${nodes.filter(m=>mastered.includes(m.id)).length}/${nodes.length} nodos</span></div><div class="g-node-grid">${nodes.map(node).join('')}</div><article class="g-boss-card"><div class="g-boss-icon">${icon(done?'shield':'bug')}</div><div><p class="eyebrow">INCIDENTE ${index+1} · ${done?'RESUELTO':'DISPONIBLE'}</p><h3>${h(inc.title)}</h3><p>3 decisiones con corrección automática. Recomendado tras los módulos ${inc.modules}.</p></div><div class="g-boss-actions"><span class="g-xp-tag">${done?'XP conseguidos':'Hasta +'+(inc.bonus+75)+' XP'}</span>${link('#/incident/'+inc.id,done?'Revisar incidente':'Investigar','secondary')}</div></article></section>`;}).join('');
  }
  function missionCard(m,compact=false){
    const value=m.checks.reduce((n,[v,t])=>n+Math.min(v,t),0),target=m.checks.reduce((n,[,t])=>n+t,0);
    return `<${compact?'div':'article'} class="${compact?'g-mission-inline':'card g-mission-card'} ${m.claimed?'is-claimed':''}"><div class="g-mission-top"><span class="g-mission-icon">${icon(m.icon)}</span><span class="g-xp-tag">${m.claimed?'Recompensa recibida':'+'+m.xp+' XP'}</span></div><h3>${h(m.title)}</h3><p>${h(m.text)}</p><div class="g-mission-checks">${m.checks.map(([v,t,label])=>`<div><span>${h(label)}</span><strong>${Math.min(v,t)}/${t}</strong></div>`).join('')}</div>${bar(Math.round(value/target*100),'Avance de '+m.title)}<div class="g-mission-action">${m.claimed?'<span class="badge accent">✓ Misión completada</span>':m.ready?`<button class="btn primary" data-action="game-claim" data-id="${m.id}">Recoger +${m.xp} XP ${icon('award')}</button>`:link(m.href,'Avanzar en la misión','secondary')}</div></${compact?'div':'article'}>`;
  }
  function missions(){
    const list=GameRules.missions(state()),pending=list.filter(m=>m.ready&&!m.claimed).length;
    return pageHead('TABLÓN DE MISIONES','Aprender tiene su recompensa.','Objetivos que combinan teoría, práctica y diagnóstico. Cada recompensa se recoge una sola vez.',`<span class="badge accent">${state().game.claimed.length}/${list.length} completadas</span>`)+
      (pending?`<div class="callout"><strong>${pending} ${pending===1?'recompensa lista':'recompensas listas'}.</strong> Has cumplido los requisitos. Recoge tus XP en las tarjetas.</div>`:'')+
      `<div class="grid-2">${list.map(m=>missionCard(m)).join('')}</div><div class="callout">Las misiones no caducan. Usar pistas, equivocarte o descansar no resta puntos. Las realizaciones de lecciones, ejercicios, retos y diagnósticos se basan en autoevaluación.</div>`;
  }
  function incident(id){
    const inc=GameData.incidents.find(x=>x.id===id);if(!inc)return UI.empty('Incidente no encontrado','Selecciona uno de los tres incidentes de la campaña.');
    const solved=state().game.incidents[id]||[],complete=GameRules.incidentDone(state(),id);
    return `<a class="back-link" href="#/operations">${icon('arrow')} Volver a la campaña</a>`+pageHead(`INCIDENTE ${id.slice(1)} · MÓDULOS ${inc.modules}`,inc.title,inc.subtitle,`<span class="g-xp-tag">${complete?'Incidente resuelto':'Hasta '+(inc.bonus+75)+' XP'}</span>`)+
      `<div class="card g-incident-status"><strong>${solved.length} de ${inc.steps.length} decisiones resueltas</strong>${bar(Math.round(solved.length/inc.steps.length*100),'Resolución del incidente')}<p class="tiny">+25 XP por decisión correcta y +${inc.bonus} XP al resolver las tres. Puedes corregir errores sin penalización. No se ejecuta código.</p></div>`+
      inc.steps.map((step,n)=>{const done=solved.includes(n);return `<article class="card g-incident-step" id="incident-${id}-${n}"><span class="badge ${done?'accent':''}">${done?'✓ Decisión resuelta':'Diagnóstico pendiente'}</span><h2>${h(step.title)}</h2><p>${h(step.text)}</p>${UI.code(step.code,'Evidencia del incidente',false)}<fieldset><legend class="sr-only">${h(step.title)}: elige una solución</legend><div class="answer-options">${step.options.map((option,index)=>`<label class="answer-option"><input type="radio" name="incident-${id}-${n}" value="${index}" ${done?'disabled':''} ${done&&index===step.answer?'checked':''}><span><code>${h(option)}</code></span></label>`).join('')}</div></fieldset>${done?'':`<button class="btn secondary" data-action="game-incident" data-id="${id}" data-step="${n}">Comprobar decisión ${icon('check')}</button>`}<div id="incident-feedback-${id}-${n}" class="g-incident-feedback" tabindex="-1" aria-live="polite">${done?`<p class="callout"><strong>Decisión correcta.</strong> ${h(step.explanation)}</p>`:''}</div></article>`;}).join('')+
      (complete?`<section class="g-resolution card"><span class="g-emblem">${icon('shield')}</span><div><p class="eyebrow">INCIDENTE RESUELTO</p><h2>Diagnóstico cerrado. Conocimiento ganado.</h2><p>Has obtenido ${inc.bonus+75} XP en total por este incidente. Revisarlo no duplica la recompensa.</p>${link('#/operations','Volver a operaciones','primary')}${link('#/missions','Revisar misiones','ghost','flag')}</div></section>`:'');
  }
  return {home,player,daily,operations,missions,incident,xpTag,missionCard};
})();
