"""Pruebas opcionales de gamificación. Requiere Playwright y Chromium.
En este entorno se usa Storage sintético en about:blank por restricciones de navegación.
No verifica persistencia nativa, red ni Pyodide. El shim solo existe en estas pruebas.
"""
from pathlib import Path
import json,os
from playwright.sync_api import sync_playwright
from build_standalone import build
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'tests'/'output';OUT.mkdir(parents=True,exist_ok=True)
STANDALONE=OUT/'test-game.html';build(STANDALONE)
html=STANDALONE.read_text()
shim='''<script>class TestStorage{constructor(){this.data={};}getItem(k){return this.data[k]??null;}setItem(k,v){this.data[k]=String(v);}removeItem(k){delete this.data[k];}}Object.defineProperty(window,'localStorage',{value:new TestStorage()});</script>'''
checks=[];errors=[]
def check(label,condition):
 assert condition,label
 checks.append(label)
 if len(checks)%20==0: print(f"Verificadas {len(checks)} comprobaciones",flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True,executable_path=os.environ.get('PYLAB_CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1440,'height':1000})
 page.set_default_timeout(4500)
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content(html.replace('<head>','<head>'+shim),wait_until='load')
 def nav(route):
  page.evaluate('(r)=>{location.hash=r;App.render();}',route)
  page.wait_for_timeout(40)
 def xp():return page.evaluate('GameRules.summary(Progress.state).xp')
 check('Inicio: identidad de operaciones',page.locator('.g-player').count()==1)
 check('Inicio: 14 nodos accesibles',page.locator('.g-network-node').count()==14)
 check('Inicio: objetivo personal',page.locator('.g-daily').count()==1)
 check('Menú de campaña, misiones y perfil',page.locator('nav [data-route=operations],nav [data-route=missions],nav [data-route=profile]').count()==3)
 check('Nivel inicial visible',page.locator('#game-profile-chip').inner_text().strip()=='Nv. 1')
 nav('/operations')
 check('Campaña: 14 nodos',page.locator('.g-module-node').count()==14)
 check('Campaña: 3 incidentes',page.locator('.g-boss-card').count()==3)
 check('Nada bloquea el acceso al módulo final',page.locator('.g-module-node[href="#/module/14"]').count()==1)
 nav('/missions');check('8 misiones visibles',page.locator('.g-mission-card').count()==8)
 check('Ninguna misión inicial se puede cobrar sin aprender',page.locator('[data-action=game-claim]').count()==0)
 nav('/profile');check('Colección de 12 insignias',page.locator('.g-award').count()==12)
 check('Escalera de 10 niveles',page.locator('.g-level').count()==10)
 check('6 emblemas disponibles',page.locator('[data-action=game-avatar]').count()==6)
 check('3 temas inicialmente bloqueados',page.locator('[data-action=game-palette]:disabled').count()==3)
 check('Reglas distinguen la autoevaluación', 'No es una nota académica' in page.locator('main').inner_text())
 nav('/lesson/m01-l1');check('Lección anuncia 25 XP', '+25 XP' in page.locator('main .g-xp-tag').inner_text())
 page.locator('[data-action=complete]').click();check('Completar lección actualiza XP',xp()==25)
 check('Recompensa visible sin modal',page.locator('#game-reward').evaluate('(e)=>e.classList.contains("visible")'))
 check('Lección completada muestra XP conseguidos','XP conseguidos' in page.locator('main .g-xp-tag').inner_text())
 page.locator('[data-action=complete]').click();page.locator('[data-action=complete]').click()
 check('Repetir marcado no infla XP',xp()==25)
 check('Objetivo diario no duplica la misma actividad',page.evaluate('GameRules.daily(Progress.state).done')==1)
 nav('/lesson/m01-l2');page.locator('[data-action=complete]').click();check('2 lecciones conceden insignia original',page.evaluate('GameRules.badges(Progress.state).find(b=>b.id==="first").earned'))
 for eid in ['e01','e02']:
  nav('/exercise/'+eid);page.locator('[data-action=complete]').click()
 nav('/quiz/1')
 page.locator('#quiz-submit').click();before=xp()
 check('Quiz vacío no da puntos',page.evaluate('!Progress.state.quizzes[1]'))
 def fill_quiz(mid):
  page.evaluate('''mid=>{const f=document.querySelector('#quiz-form');for(const q of Course.quizzes.filter(q=>q.module===mid)){if(q.type==='fill')f.elements[q.id].value=q.answer[0];else for(const i of Array.isArray(q.answer)?q.answer:[q.answer])f.querySelector(`input[name="${q.id}"][value="${i}"]`).checked=true;}Quiz.updateStatus();}''',mid)
 fill_quiz(1);page.locator('#quiz-submit').click()
 check('Quiz perfecto y dominio del módulo suman 240 XP',xp()-before==240)
 check('Corrección conserva las 6 explicaciones',page.locator('.quiz-feedback.correct').count()==6)
 check('Indicador de recompensa lista en el menú',page.locator('#game-mission-count').inner_text()=='1')
 nav('/missions');before=xp();page.locator('[data-action=game-claim][data-id=first]').click()
 check('Botón recoger recompensa concede 100 XP',xp()-before==100)
 check('Misión recogida no presenta botón de cobro',page.locator('[data-action=game-claim][data-id=first]').count()==0)
 nav('/quiz/1');fill_quiz(1);before=xp();page.locator('#quiz-submit').click();check('Quiz repetido al 100% no duplica XP',xp()==before)
 nav('/predict?module=1');before=xp();page.locator('[data-action=predict-show]').click();check('Ver solución de predicción no concede XP',xp()==before)
 page.locator('#answer-p01').fill('incorrecto');page.locator('[data-action=predict-check]').click();check('Predicción errónea no resta ni suma',xp()==before)
 page.locator('#answer-p01').fill(page.evaluate('Course.predictions[0].output'));page.locator('[data-action=predict-check]').click();check('Predicción correcta da 40 XP',xp()==before+40)
 page.locator('[data-action=predict-check]').click();check('Predicción repetida sin XP extra',xp()==before+40)
 nav('/debug?module=1');before=xp();button=page.locator('[data-action=game-debug]');button.click()
 check('Diagnóstico vacío no obtiene XP',xp()==before)
 bug_id=page.evaluate('Course.bugs[0].id')
 page.locator('#diagnosis-'+bug_id).fill('He revisado el tipo de error, la instrucción incorrecta y he contrastado la solución de referencia.')
 button.click();check('Diagnóstico sin contraste confirmado no obtiene XP',xp()==before)
 page.locator('details summary').click();page.locator('#reviewed-'+bug_id).check();button.click()
 check('Diagnóstico autoevaluado da 30 XP',xp()==before+30)
 check('Diagnóstico impide cobrar de nuevo',button.is_disabled())
 nav('/incident/i01');before=xp();page.locator('[data-action=game-incident]').first.click()
 check('Incidente sin elección no da XP',xp()==before)
 page.locator('input[name="incident-i01-0"][value="0"]').check();page.locator('[data-action=game-incident]').first.click()
 check('Decisión incorrecta sin penalización','No pierdes puntos' in page.locator('#incident-feedback-i01-0').inner_text() and xp()==before)
 for n in range(3):
  answer=page.evaluate('(n)=>GameData.incidents[0].steps[n].answer',n)
  page.locator(f'input[name="incident-i01-{n}"][value="{answer}"]').check()
  page.locator(f'[data-action=game-incident][data-step="{n}"]').click()
  check('Decisión del incidente guardada '+str(n),page.evaluate('(n)=>Progress.state.game.incidents.i01.includes(n)',n))
 check('Incidente completo da 200 XP',xp()==before+200)
 check('Pantalla de resolución visible',page.locator('.g-resolution').count()==1)
 check('Todas las respuestas resueltas se bloquean',page.locator('.g-incident-step input:not(:disabled)').count()==0)
 nav('/incident/i01');check('Decisiones se conservan al regresar',page.locator('.g-resolution').count()==1 and page.locator('[data-action=game-incident]').count()==0)
 nav('/profile');page.locator('#game-alias').fill('Equipo Python Ops');page.locator('#game-goal').select_option('5');page.locator('[name=effects]').uncheck();page.locator('#game-profile-form [type=submit]').click()
 check('Alias guardado y mostrado','Equipo Python Ops' in page.locator('.g-player h2').inner_text())
 check('Objetivo de 5 guardado',page.evaluate('Progress.state.game.profile.goal')==5)
 check('Animaciones desactivables',page.locator('html').get_attribute('data-effects')=='off')
 page.locator('[data-action=game-avatar][data-id=shield]').click();check('Emblema actualizable',page.evaluate('Progress.state.game.profile.avatar')=='shield')
 check('Tema azul desbloqueado en nivel 3 o superior',not page.locator('[data-action=game-palette][data-id=blue]').is_disabled())
 page.locator('[data-action=game-palette][data-id=blue]').click();check('Tema desbloqueado puede equiparse',page.locator('html').get_attribute('data-palette')=='blue')
 page.locator('#theme-toggle').click();check('Tema claro respeta paleta',page.locator('html').get_attribute('data-theme')=='light' and page.locator('html').get_attribute('data-palette')=='blue')
 page.locator('#theme-toggle').click()
 # Exportación e importación de toda la capa de juego a través de controles reales.
 backup=page.evaluate('JSON.stringify(Progress.state)');before=xp();nav('/progress')
 with page.expect_download() as download:page.locator('[data-action=export]').click()
 downloaded=json.loads(Path(download.value.path()).read_text())
 check('Exportación incluye perfil e incidentes',downloaded['game']['profile']['alias']=='Equipo Python Ops' and len(downloaded['game']['incidents']['i01'])==3)
 page.locator('[data-action=reset-progress]').click();page.locator('#confirm-cancel').click();check('Cancelar reinicio mantiene XP',xp()==before)
 page.locator('[data-action=reset-progress]').click();page.locator('#confirm-accept').click()
 check('Reinicio borra gamificación',xp()==0 and page.evaluate('Progress.state.game.claimed.length')==0)
 check('Reinicio retira recompensa antigua',not page.locator('#game-reward').evaluate('(e)=>e.classList.contains("visible")'))
 page.locator('#progress-import').set_input_files({'name':'game.json','mimeType':'application/json','buffer':backup.encode()});page.locator('#confirm-accept').click()
 check('Importar recupera XP, perfil y misiones',xp()==before and page.evaluate('Progress.state.game.profile.alias')=='Equipo Python Ops' and page.evaluate('Progress.state.game.claimed.includes("first")'))
 old={'version':1,'lessons':['m01-l1'],'exercises':['e01'],'challenges':[],'quizzes':{},'days':[],'lastLesson':'m01-l1','lastModule':1}
 page.locator('#progress-import').set_input_files({'name':'old.json','mimeType':'application/json','buffer':json.dumps(old).encode()});page.locator('#confirm-accept').click()
 check('Interfaz importa copia antigua con XP retroactivos',xp()==60)
 nav('/profile');page.locator('#game-alias').fill('<img src=x>');page.locator('#game-profile-form [type=submit]').click()
 check('Alias se escapa, no se interpreta como HTML',page.locator('.g-player h2').inner_text()=='<img src=x>' and page.locator('.g-player img').count()==0)
 # Demo sin datos personales para inspección visual.
 page.evaluate('''()=>{Progress.reset();Progress.profile({alias:'Demo · Python Ops'});for(const m of [1,2,3,4]){for(const l of Course.lessons.filter(x=>x.module===m))Progress.toggle('lessons',l.id);for(const x of Course.exercises.filter(x=>x.module===m).slice(0,2))Progress.toggle('exercises',x.id);Progress.quiz(m,100);}Progress.claim('first');Progress.claim('foundation');Progress.incident('i01',0);Progress.incident('i01',1);Progress.incident('i01',2);Progress.profile({effects:false});}''')
 page.wait_for_timeout(5100)
 nav('/home');page.screenshot(path=str(OUT/'game-home-desktop.png'),full_page=True)
 nav('/operations');page.screenshot(path=str(OUT/'game-campaign-desktop.png'),full_page=True)
 nav('/profile');page.screenshot(path=str(OUT/'game-profile-desktop.png'),full_page=True)
 page.locator('#theme-toggle').click();nav('/home');page.screenshot(path=str(OUT/'game-home-light.png'),full_page=True);page.locator('#theme-toggle').click()
 for width in [320,390,768,1024,1440]:
  page.set_viewport_size({'width':width,'height':900})
  for route in ['/home','/operations','/missions','/profile','/incident/i02','/lesson/m08-l2','/exercise/e52','/challenge/r12','/quiz/14','/predict','/debug','/progress']:
   nav(route)
   check(f'Sin desbordamiento {width}px {route}',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  if width==390:
   nav('/home');page.screenshot(path=str(OUT/'game-home-mobile.png'),full_page=True)
   page.locator('#menu-toggle').click();check('Menú móvil da acceso a campaña',page.locator('.nav-link[data-route=operations]').is_visible())
   page.locator('.nav-link[data-route=operations]').click();page.wait_for_timeout(100)
   check('Elegir campaña cierra el menú móvil',page.locator('#sidebar').evaluate('(el)=>!el.classList.contains("open")'))
   page.screenshot(path=str(OUT/'game-campaign-mobile.png'),full_page=True)
 page.emulate_media(reduced_motion='reduce')
 check('Respeta movimiento reducido del navegador',page.locator('#game-reward').evaluate('(el)=>getComputedStyle(el).transitionDuration')=='0s')
 # Estructura de todas las rutas nuevas y vínculos de acción válidos.
 page.set_viewport_size({'width':1440,'height':1000})
 for route in ['/home','/operations','/missions','/profile','/incident/i01','/incident/i02','/incident/i03']:
  nav(route);check('Un único H1 '+route,page.locator('main h1').count()==1)
 check('Sin errores JavaScript observados',not errors)
 browser.close()
report={'passed':len(checks),'checks':checks,'javascript_errors':errors,'method':'Chromium con recursos integrados y Storage sintético. No prueba persistencia nativa, red ni ejecución de Pyodide.'}
(ROOT/'tests/results/game-ui-results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print(json.dumps({'passed':len(checks),'javascript_errors':errors},ensure_ascii=False))
