type Player
  @table(name: "players", key: "id")
  @unique(fields: ["id", "clubId"])
{
  id: UUID! @default(expr: "uuidV4()")
  club: Club! @ref(fields: "clubId")
  clubId: UUID! @col(name: "club_id")
  sourceInscription: Inscription
    @ref(fields: ["sourceInscriptionId", "clubId"], references: ["id", "clubId"])
  sourceInscriptionId: UUID @col(name: "source_inscription_id") @unique
  firstName: String! @col(name: "first_name")
  lastName: String! @col(name: "last_name")
  nationalId: String! @col(name: "national_id")
  birthDate: Date! @col(name: "birth_date")
  phone: String
  email: String
  address: String
  joinedOn: Date! @col(name: "joined_on")
  status: String!
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}

type Staff
  @table(name: "staff", key: "id")
  @unique(fields: ["id", "clubId"])
{
  id: UUID! @default(expr: "uuidV4()")
  club: Club! @ref(fields: "clubId")
  clubId: UUID! @col(name: "club_id")
  firstName: String! @col(name: "first_name")
  lastName: String! @col(name: "last_name")
  nationalId: String @col(name: "national_id")
  phone: String
  email: String
  address: String
  defaultRole: String @col(name: "default_role")
  status: String!
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}

type Team
  @table(name: "teams", key: "id")
  @unique(fields: ["id", "clubId"])
  @unique(fields: ["id", "seasonId", "clubId"])
  @unique(fields: ["clubId", "seasonId", "name"])
{
  id: UUID! @default(expr: "uuidV4()")
  club: Club! @ref(fields: "clubId")
  clubId: UUID! @col(name: "club_id")
  season: Season! @ref(fields: ["seasonId", "clubId"], references: ["id", "clubId"])
  seasonId: UUID! @col(name: "season_id")
  name: String!
  competition: String
  category: String
  status: String!
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}

type PlayerSeason
  @table(name: "player_seasons", key: ["player", "season"])
{
  club: Club! @ref(fields: "clubId")
  clubId: UUID! @col(name: "club_id")
  player: Player! @ref(fields: "playerId")
  playerId: UUID! @col(name: "player_id")
  season: Season! @ref(fields: "seasonId")
  seasonId: UUID! @col(name: "season_id")
  category: String
  status: String!
  joinedOn: Date @col(name: "joined_on")
  leftOn: Date @col(name: "left_on")
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}

type PlayerTeam
  @table(name: "player_teams", key: ["player", "team"])
{
  club: Club! @ref(fields: "clubId")
  clubId: UUID! @col(name: "club_id")
  player: Player! @ref(fields: "playerId")
  playerId: UUID! @col(name: "player_id")
  team: Team! @ref(fields: "teamId")
  teamId: UUID! @col(name: "team_id")
  season: Season! @ref(fields: "seasonId")
  seasonId: UUID! @col(name: "season_id")
  startDate: Date @col(name: "start_date")
  endDate: Date @col(name: "end_date")
  status: String!
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}

type StaffTeam
  @table(name: "staff_teams", key: ["staffId", "teamId"])
{
  club: Club! @ref(fields: "clubId")
  clubId: UUID! @col(name: "club_id")
  staff: Staff!  @ref(fields: "staffId")
  staffId: UUID! @col(name: "staff_id")
  team: Team! @ref(fields: "teamId")
  teamId: UUID! @col(name: "team_id")
  season: Season! @ref(fields: "seasonId")
  seasonId: UUID! @col(name: "season_id")
  role: String!
  startDate: Date @col(name: "start_date")
  endDate: Date @col(name: "end_date")
  status: String!
  createdAt: Timestamp! @col(name: "created_at") @default(expr: "request.time")
  updatedAt: Timestamp! @col(name: "updated_at") @default(expr: "request.time")
}
